### PR TITLE
CD-226 cd-card

### PR DESCRIPTION
**Pull request by left23**
Review of the `cd-card` component

See https://feature.commondesign-unocha-org.ahconu.org/demo#cd-card for an example

See https://humanitarian.atlassian.net/browse/CD-249

### CODE REVIEW

**Comment by left23** [comment]
I noticed in `cd-event` component there should probably be a variant listed on the `cd-card` component as described in README https://github.com/UN-OCHA/common_design/blob/cd-226-design-system/components/cd-event/README.md

**Review by lazysoundsystem — APPROVED** [review]
Added 1px to the media query for consistency - if it breaks something, do change it back.

Thinking again about making the whole card clickable, which maybe has more of a case here than in https://github.com/UN-OCHA/common_design/pull/157 - I also found this implementation, which has some other suggestions too: https://inclusive-components.design/cards/

But as it is it works well and is intuitive.

**Comment by left23** [comment]
@lazysoundsystem Should there be a commit from you on this branch?

**Comment by lazysoundsystem** [comment]
Yes, not sure what happened there. Also, edited my last comment - the media query change was for another component.

**Pull request merged**
