### PR TITLE
CD-269: use npm-watch to lint+compile on each filesave

### PR DESCRIPTION
**Pull request by rupl**
Adds a lint-on-save function to the ongoing PR #191

### CODE REVIEW

**Comment by left23** [comment]
@rupl Thanks.
This matches the current Gulp set up, where the linting runs on watch (as part of `gulp dev`). For me, this is handy because I can fix the linting issues as I go. The alternative (if we don't merge this PR) would be to get the list of warnings when running `sass:build` either manually or as part of the pre-commit git hook or via travis, which is also reasonable.

@orakili @lazysoundsystem Did you use the `gulp` or `gulp dev` task (which has the watcher) in the past when you worked on the sub themes? Or did you compile after you made some changes using `gulp build`?

**Comment by lazysoundsystem** [comment]
Not often, no - generally when I've made changes to the styling I've used `gulp sass`.

**Comment by orakili** [comment]
I also tend to simply use `gulp sass` (linting is set to run when saving in my editor).

**Comment by rupl** [comment]
I'm also ok with running the linter on Travis and reacting to it when desired, instead of every filesave. The command can always be run manually. I only put the PR together because of our discussion in #191 and I assumed it was your wish to restore this bit of the workflow.

Happy to close this if our team won't get much regular use out of it 👍

**Comment by left23** [comment]
@rupl Thanks for preparing this. It's a nice option for the future if I really feel the linting is missing from the watch process. I should have asked people's opinion beforehand. In order not to add another dependency, I think we can close this without merging.

**Pull request closed without merging**
